CREATE TABLE AUDITORIA(
ID_AUDITORIA INT IDENTITY (1,1) NOT NULL,
TIPO_AUDITORIA VARCHAR(20) NOT NULL,
FECHA DATETIME NOT NULL,
DESCRIPCION VARCHAR(50),
NOMBRE_USUARIO VARCHAR(20),
APELLIDO_USUARIO VARCHAR(20),
NOMBRE_SERVICIO VARCHAR(30),
PRIMARY KEY(ID_AUDITORIA))