CREATE TRIGGER AUDITORIA_PACIENTE_INSERTAR
ON PACIENTE
FOR INSERT
AS
BEGIN
INSERT AUDITORIA SELECT 'DESCONOCIDO', GETDATE(), 'INSERTO PACIENTE', (SELECT COUNT(NOMBRE) FROM PACIENTE), 
(SELECT COUNT(APELLIDO) FROM PACIENTE),(SELECT NOMBRE_SERVICIO FROM SERVICIO)  FROM INSERTED
END;
