CREATE TRIGGER AUDITORIA_PACIENTE_ACTUALIZAR
ON PACIENTE
FOR UPDATE
AS
BEGIN
INSERT AUDITORIA SELECT  'DESCONOCIDO', GETDATE(), 'ACTUALIZO PACIENTE',(SELECT COUNT(NOMBRE) FROM PACIENTE),
(SELECT COUNT(APELLIDO) FROM PACIENTE), (SELECT NOMBRE_SERVICIO FROM SERVICIO) FROM UPDATED
END;
