CREATE TRIGGER AUDITORIA_PACIENTE_BORRAR
ON PACIENTE
FOR DELETE
AS
BEGIN
INSERT AUDITORIA SELECT  'DESCONOCIDO', GETDATE(), 'BORRO PACIENTE',(SELECT COUNT(NOMBRE) FROM PACIENTE),
(SELECT COUNT(APELLIDO) FROM PACIENTE), (SELECT NOMBRE_SERVICIO FROM SERVICIO) FROM DELETED
END;