CREATE TRIGGER AUDITORIA_SERVICIO_INSERTAR
ON SERVICIO
FOR INSERT
AS
BEGIN
INSERT AUDITORIA SELECT  'DESCONOCIDO', GETDATE(), 'INSERTO SERVICIO',(SELECT COUNT(NOMBRE) FROM PACIENTE),
(SELECT COUNT(APELLIDO) FROM PACIENTE), (SELECT NOMBRE_SERVICIO FROM SERVICIO) FROM INSERTED
END;
