CREATE TRIGGER AUDITORIA_SERVICIO_BORRAR
ON SERVICIO
FOR DELETE
AS
BEGIN
INSERT AUDITORIA SELECT 'DESCONOCIDO', GETDATE(), 'BORRO SERVICIO',(SELECT COUNT(NOMBRE) FROM PACIENTE),
(SELECT COUNT(APELLIDO) FROM PACIENTE), (SELECT NOMBRE_SERVICIO FROM SERVICIO) FROM DELETED
END;